# Generated by Django 5.2.6 on 2025-09-12 02:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('link', models.URLField(max_length=255)),
                ('publico_alvo', models.CharField(max_length=100, verbose_name='Público-Alvo')),
            ],
            options={
                'verbose_name': 'Guia Informativo',
                'verbose_name_plural': 'Guias Informativos',
            },
        ),
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rotina',
                'verbose_name_plural': 'Rotinas',
            },
        ),
        migrations.CreateModel(
            name='ItemRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='rotinas/itens/')),
                ('ordem', models.PositiveIntegerField()),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.rotina', verbose_name='Rotina')),
            ],
            options={
                'verbose_name': 'Item de Rotina',
                'verbose_name_plural': 'Itens de Rotina',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('TEA', 'Pessoa com TEA'), ('CUIDADOR', 'Cuidador'), ('EDUCADOR', 'Educador'), ('ADM', 'Administrador')], max_length=10, verbose_name='Tipo de Usuário')),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/perfis/', verbose_name='Imagem de Perfil')),
                ('groups', models.ManyToManyField(blank=True, related_name='app_usuario_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='app_usuario_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='rotina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='app.usuario', verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PerfilApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_emergencia', models.CharField(blank=True, max_length=100, verbose_name='Contato de Emergência')),
                ('informacoes_medicas', models.TextField(blank=True, verbose_name='Informações Médicas')),
                ('gostos_interesses', models.TextField(blank=True, verbose_name='Gostos e Interesses')),
                ('comportamentos_sensoriais', models.TextField(blank=True, verbose_name='Comportamentos Sensoriais')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_apoio', to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Apoio',
                'verbose_name_plural': 'Perfis de Apoio',
            },
        ),
        migrations.CreateModel(
            name='PECs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pecs/')),
                ('texto', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecs', to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'PECs',
                'verbose_name_plural': 'PECs',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.postagem', verbose_name='Postagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['data'],
            },
        ),
    ]
