# Generated by Django 5.2.6 on 2025-10-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecs',
            name='is_crisis_card',
            field=models.BooleanField(default=False, verbose_name='É um cartão de crise?'),
        ),
    ]
