# Generated by Django 5.2.6 on 2025-11-23 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiainformativo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Publicação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guiainformativo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='guias/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='guiainformativo',
            name='descricao',
            field=models.TextField(verbose_name='Conteúdo do Guia'),
        ),
        migrations.AlterField(
            model_name='guiainformativo',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link Externo (Opcional)'),
        ),
        migrations.AlterField(
            model_name='guiainformativo',
            name='publico_alvo',
            field=models.CharField(max_length=100, verbose_name='Público Alvo'),
        ),
        migrations.AlterField(
            model_name='guiainformativo',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
