# Generated by Django 5.2.6 on 2025-11-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_guiainformativo_data_criacao_guiainformativo_imagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='postagem',
            name='categoria',
            field=models.CharField(choices=[('DUVIDA', 'Dúvida'), ('RELATO', 'Relato de Experiência'), ('DICA', 'Dica ou Sugestão'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
    ]
