# Generated by Django 5.2.6 on 2025-12-01 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_postagem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiainformativo',
            name='autor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='guias_criados', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
